<?php

namespace Database\Seeders;

use App\Models\Siswa;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $siswa = Siswa::insert([
            [
                'nama' => 'ABU BAKAR TSABIT GHUFRON', 
                'nis' => '20388',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '085839328609',
                'email' => 'makinamikayumi@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'MUTIARA SEKAR KINASIH', 
                'nis' => '20431',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Bantul',
                'kontak' => '085198553807',
                'email' => 'mtiaraskinasih@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'ADE ZAIDAN ALTHAF', 
                'nis' => '20390',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Gunungkidul',
                'kontak' => '087786760589',
                'email' => 'adezaidan24@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'ANGELINA THITHIS SEKAR LANGIT', 
                'nis' => '20396',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Madurejo',
                'kontak' => '081272353535',
                'email' => 'sekarsayang@aryok.tech',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'ARYA EKA RAHMAT PRASETYO',
                'nis' => '20399',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Berbah',
                'kontak' => '082265468133',
                'email' => 'sayang',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'MARCELLINUS CHRISTO PRADIPTA', 
                'nis' => '20422',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '089688361696',
                'email' => 'marchllinuschristo11@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'NAUFELIRNA SUBKHI RAMADHANI', 
                'nis' => '20454',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Klaten',
                'kontak' => '089671421234',
                'email' => 'adzanaufel705@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'ROSYIDAH MUTHMAINNAH', 
                'nis' => '20448',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '087883538770',
                'email' => 'rosyi.html@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'GABRIEL POSSENTI GENTA BAHANA NAGARI', 
                'nis' => '20410',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Sleman',
                'kontak' => '089634085990',
                'email' => 'gentapossenti@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'NAFISYA RHEA PRAYASTI', 
                'nis' => '20865',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Bantul',
                'kontak' => '08816752848',
                'email' => 'nafisyarhea29@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'FARCHA AMALIA NUGRAHAINI', 
                'nis' => '20408',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Sleman',
                'kontak' => '0895380761274',
                'email' => 'farchaamalia@gmail.com',
                'status_lapor_pkl'=> false,
            ],
            [
                'nama' => 'GISELO KRISTIYANTO',
                'nis' => '20412',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567814',
                'email' => '20412@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'INTAN LUVIA HISANAH',
                'nis' => '20414',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567815',
                'email' => '20414@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'ISNAINI NUR WAHYUNINGSIH',
                'nis' => '20415',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567816',
                'email' => '20415@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'IZZUDDIN FAYYEDH HAQ',
                'nis' => '20416',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567817',
                'email' => '20416@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'JARDELLA ANGGUN LAVATEKTONIA',
                'nis' => '20417',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567818',
                'email' => '20417@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'JECONIA VALE ADYATMA',
                'nis' => '20418',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567819',
                'email' => '20418@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'KAYSA AQILA AMTA',
                'nis' => '20419',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567820',
                'email' => '20419@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'KEVIN ANDREA GERALDINO',
                'nis' => '20420',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567821',
                'email' => '20420@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'LAURENTIUS ANTARA',
                'nis' => '20421',
                'rombel' => 'A',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567822',
                'email' => '20421@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'MEIDINNA TIARA AMELIA',
                'nis' => '20423',
                'rombel' => 'A',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567824',
                'email' => '20423@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'MICHAEL FARIAN',
                'nis' => '20424',
                'rombel' => 'B',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567825',
                'email' => '20424@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'MUSTAFA RAMADHAN',
                'nis' => '20425',
                'rombel' => 'B',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567826',
                'email' => '20425@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'NAJLA ARUM SARI',
                'nis' => '20426',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567827',
                'email' => '20426@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'NADIA SYIFA MAHESWARI',
                'nis' => '20427',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567828',
                'email' => '20427@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'NADIA SAFAH',
                'nis' => '20428',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567829',
                'email' => '20428@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'NABILLA RAFAELLA CATHRINA',
                'nis' => '20429',
                'rombel' => 'B',
                'gender' => 'P',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567830',
                'email' => '20429@sija.com',
                'status_lapor_pkl' => false,
            ],
            [
                'nama' => 'NATHAN ALDO PRATAMA',
                'nis' => '20430',
                'rombel' => 'B',
                'gender' => 'L',
                'alamat' => 'Alamat siswa',
                'kontak' => '1234567831',
                'email' => '20430@sija.com',
                'status_lapor_pkl' => false,
            ],
        ]);
    }
}